name: Playwright Tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/playwright.yml'
      - 'package.json'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/playwright.yml'
      - 'package.json'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json', '**/bun.lockb') }}

    - name: Install Playwright browsers
      run: bun run test:setup

    - name: Run Playwright tests
      run: bun run test --project chromium

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30