name: Code quality

on:
  push:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.mdx'
      - '**.json'
      - '**.yaml'

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .
